repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=4', '--top-keys=comma']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: pytest
        stages: [pre-push]
        name: Run pytest tests
        entry: bash -c 'if [ -z "$SKIP_TESTS" ]; then pytest --maxfail=1 --disable-warnings -q; else echo "Skipping tests"; fi'
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.9
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [pyproject.toml, -o, requirements.txt]
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args: [--group, dev, -o, requirements-dev.txt]
        files: ^requirements-dev\.(in|txt)$
      - id: uv-lock
