version = "2.0.0"

[development]
development = true

[bot]
bot_id = 707980467
color = 0x9147FF
dev_userid = 411010313
dev_name = "mr_chuw"  # This name will be replaced by twitch name when bot fully starts, its used on start to create the channel on database, so put the our twitch nick
dev_display_name = "MrChuw"
default_prefix = "+"
allowed_prefix_list = false
allowed_prefix_size = 10
site_url = "https://gorenmu.vercel.app/"
imgur_authorized_ids = [184900613, 411010313]

[apis]
hex_site_url = "${HEX_SITE_URL}"
image_carousel = "${IMAGE_CAROUSEL}"
image_carousel_api_key = "${IMAGE_CAROUSEL_API_KEY}"
site_api_key = "${SITE_API_KEY}"
shlink_key = "${SHLINK_KEY}"
shlink_url = "${SHLINK_URL}"
access_token = "${ACCESS_TOKEN}"
access_oauth_token = "${ACCESS_OAUTH_TOKEN}"
refresh_token = "${REFRESH_TOKEN}"
client_id = "${CLIENT_ID}"

api_client_id = "${API_CLIENT_ID}"
api_client_secret = "${API_CLIENT_SECRET}"

pastbin_url="https://bin.mrchuw.com.br/documents"
file_upload_url = "${FILE_UPLOAD_URL}"
enable_site_endpoints = true

[database]
type = "mariadb"
login = "${DB_LOGIN}"
password = "${DB_PASSWORD}"
host = "127.0.0.1"
port = 3307
name = "${DB_NAME}"

[cache]
type = "memory"
host = "${REDIS_HOST}"
port = "${REDIS_PORT}"
password = "${REDIS_PASSWORD}"
namespace = "${REDIS_NAMESPACE}"
db = "${REDIS_DB}"


[logger]
format = "{time:YYYY-MM-DD HH:mm:ss} [{level}] {name} {module}.py:{line} {message}"
level = "INFO"
enqueue = true
colorize = true
