services:
  Gorenmu_bot:
    build:
      context: .
    image: gorenmu-bot:latest
    container_name: Gorenmu
    tty: true
    working_dir: /app
    network_mode: host
    environment:
      - UV_PYTHON_PREFERENCE=only-managed
      - UV_CACHE_DIR=/uv-cache
      - UV_PYTHON_INSTALL_DIR=/uv-python
      - UV_COMPILE_BYTECODE=1
    volumes:
      - .:/app
      - venv_data:/app/.venv
      - uv_cache_data:/uv-cache
      - uv_python:/uv-python
    command:
      bash -c "uv sync && uv run python __main__.py"
#    restart: unless-stopped

  Gorenmu_db:
    image: mariadb
    container_name: Mariadb
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.data/database:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  Gorenmu_cache:
    image: valkey/valkey:unstable
    container_name: Valkey
    tty: true
    volumes:
      - ./.data/.redis:/data
    ports:
      - "6379:6379"
    command: "valkey-server --save 60 1 --loglevel warning"
    restart: unless-stopped

  Gorenmu_cache2:
    container_name: Pogocache
    image: pogocache/pogocache
    tty: true
    volumes:
      - ./.data/.redis:/data
    ports:
      - "9401:9401"
    entrypoint: bash -c "sleep 100000"
    command: "-h 0.0.0.0 --persist=/data/data.db --evict=no"
    restart: unless-stopped

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_USER: "user"
      CLICKHOUSE_PASSWORD: "SuperSecretPassword"
    ports:
      - "15342:8123"  # interface HTTP para queries
    volumes:
      - "./.data/z_log_queries.xml:/etc/clickhouse-server/users.d/z_log_queries.xml"
      - "./.data/z_clickhouse.xml:/etc/clickhouse-server/config.d/z_system-logs-ttl.xml"
      - ./.data/.clickhouse/data:/var/lib/clickhouse
      - ./.data/.clickhouse/logs:/var/log/clickhouse-server
    restart: unless-stopped

volumes:
  venv_data:
  uv_cache_data:
  uv_python:
