[project]
name = "gorenmu"
version = "2.0.0"
description = "Twitch bot build on top of twitchio."
readme = "README.md"
requires-python = "==3.13.1"

dependencies = [
    "aiocache[memcached,redis]==0.12.3",
    "aiofile>=3.9.0",
    "aiohttp==3.12.15",
    "aiohttp-client-cache[all]==0.13.0",
    "beautifulsoup4==4.13.4",
    "clickhouse-connect>=0.10.0",
    "emoji==2.14.1",
    "fastapi==0.116.1",
    "fluent-runtime>=0.4.0",
    "humanize==4.12.3",
    "janus==2.0.0",
    "loguru==0.7.3",
    "nltk==3.9.1",
    "pillow==11.3.0",
    "psutil==7.0.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.1",
    "pytz==2025.2",
    "quickjs==1.19.4",
    "redis==6.4.0",
    "toml==0.10.2",
    "tortoise-orm[asyncmy,asyncpg]==0.25.3",
    "twitchio[starlette]==3.1.0",
    "unidecode==1.4.0",
    "urlextract==1.9.0",
    "uvicorn==0.35.0",
    "uvloop>=0.22.1",
    "watchdog==6.0.0",
    "yarl==1.20.1",
]

[dependency-groups]
dev = [
    "aioresponses==0.7.8",
    "deptry==0.24.0",
    "freezegun==1.5.5",
    "pre-commit==4.3.0",
    "pytest==8.4.1",
    "pytest-asyncio==1.1.0",
    "pytest-timeout>=2.4.0",
    "pytest-xdist==3.8.0",
    "ruff==0.14.6",
    "snakeviz==2.2.2",
    "tuna==0.5.11",
]


[tool.ruff]
line-length = 120
target-version = "py313"
exclude = [
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "models/__init__.py",
    "bot/api/*",
    "bot/apis/booru/*",
    "bot/apis/translate/*",
    "bot/apis/weather/*"
]

[tool.ruff.lint]
ignore = ["E203", "RUF100", "UP047", "B023"]
select = ["E", "F", "W", "I", "UP", "B", "C4", "ISC", "TID", "RUF", "SIM", "N", "PERF"]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
markers = ["network: tests that make real requests", "disabled: Tests that have been disabled. Reason: I don't want to find out why it's causing problems.",
    "pt_BR: Test for Portuguse language.", "en: Test for English language."]
#addopts = "-m 'not disabled'"
#addopts = "-n auto -m 'not disabled'"
addopts = "-m 'not network and not disabled'"
#addopts = "-n auto -m 'not network and not disabled'"

[tool.uv.sources]
twitchio = { git = "https://github.com/PythonistaGuild/TwitchIO.git" }
