authors:
  mrchuw:
    name: Mrchuw
    description: Creator
    avatar: https://github.com/mrchuw.png

  squidfunk:
    name: Martin Donath
    description: Contributor
    avatar: https://github.com/squidfunk.png

