authors:
  mrchuw:
    name: Mrchuw
    description: Criador
    avatar: https://github.com/mrchuw.png

  squidfunk:
    name: Martin Donath
    description: Contribuinte
    avatar: https://github.com/squidfunk.png

