from __future__ import annotations

from typing import Any, TYPE_CHECKING

from .extras import WeatherTools
from .extras import from_list_to_pet_list, pets, PetsDict
from .extras import fight_option
from .extras import dungeon_rank_dict
from .extras import Activity as ActivityExtras
from .extras import BaseTranslation
from .extras import Response
from .extras import Humanize
from .extras import Timeago
from .extras import TimeTools
from .extras import Dicio
from .extras import Values, bets_values

if TYPE_CHECKING:
    from bot.ext.commands import Context
    from bot.models import Cookies




class EnTranslations:
    class TypeChecking(BaseTranslation):
        response: Response

    class SupportTools:
        Humanize: Humanize = Humanize

        mention: str = "you"

        class TimeTools(BaseTranslation):
            TimeTools: TimeTools = TimeTools
            Timeago: Timeago = Timeago
            strftime: str = "%m/%d/%Y %I:%M %p"

        class Lottery(BaseTranslation):
            bet_or_consultation: list[str] = ["aposta", "consultar"]

        class Dicio(BaseTranslation):
            Dicio: Dicio = Dicio

    class Exceptions:
        class LotteryExceptions(BaseTranslation):
            lottery_seed: str = "something terrible happened, contact \"{}\" here on Twitch using whispers."

        class ToolsExceptions(BaseTranslation):
            announcement: str = "something went wrong with the announcement. {}"

        class BotMainLoopExceptions(BaseTranslation):
            dev_required: str = "you need to be my creator to run this command."
            owner_required: str = "commands reserved for the bot owner."
            command_on_cooldown: str = "to use the command again, come back in {}."
            not_implemented: str = "this command is temporarily disabled."

            error_not_registered: str = "an unexpected error occurred, please report the error to @{}"

        class ResponseExceptions(BaseTranslation):
            error_on_command: str = "an error occurred in the command \"{}\""
            pipe_response: str = "here is the response generated by the previous command: {}"
            command_not_pipeble: str = "this command could not be used with the pipe."

    class Admin:
        class Nada(BaseTranslation):
            nada: Response = Response({
                    "success": True,
                    "response": "The command was executed successfully."}
            )

        class Reload(BaseTranslation):
            commands_reloaded: Response = Response({
                    "success": True,
                    "response": "The commands were successfully reloaded."}
            )

        class Restart(BaseTranslation):
            success: Response = Response({"response": "The bot has been successfully restarted."})
            unexpected_error: Response = Response({"response": "There was an error restarting the bot: {}"})

    class Others:
        class Pipe(BaseTranslation):
            response: Response = Response({"response": "Pipe is not really a command. "
                                                       "For more information, visit this link: {}"})

    class Afk:
        afks: dict[str, ActivityExtras.Status] = ActivityExtras.afks

        class Afk(BaseTranslation):
            message_too_long: Response = Response({
                    "success": False,
                    "response": "This message is too long."})
            afk_response: Response = Response({
                    "success": True,
                    "response": "{}: {}"})
            afk_content_response: Response = Response({
                    "success": True,
                    "response": "{}: {} and left a note with: {}"})

        class IsAfk(BaseTranslation):
            bot_nick: Response = Response(
                    {"success": False, "response": "I'm always here... watching."}
            )
            author_nick: Response = Response(
                    {"success": False, "response": "you're not working... obviously"}
            )
            never_seen: Response = Response(
                    {"success": False, "response": "I don't remember ever seeing any {}."}
            )
            is_afk: Response = Response({"success": False, "response": "@{} {}: {}"})
            is_afk_content: Response = Response(
                    {"success": False, "response": "@{} {} and left a note: {}"}
            )
            is_not_afk: Response = Response({"success": False, "response": "@{} is not AFK."})

        class RAfk(BaseTranslation):
            time_expired: Response = Response({
                    "success": False,
                    "response": "The time to return has already passed."})
            is_afk: Response = Response({
                    "success": False,
                    "response": "{}: {}"})
            is_afk_content: Response = Response({
                    "success": False,
                    "response": "{} {} and left a note: {}"})
            is_not_afk: Response = Response({
                    "success": False,
                    "response": "you are not AFK."})

        class AfkListeners(BaseTranslation):
            is_afk: Response = Response({"success": False, "response": "{}: {} (was away for {} {})"})
            is_afk_content: Response = Response(
                    {"success": False, "response": "{} {} and left a note: {} (was away for {} {})"})

    class Alias(BaseTranslation):
        user_not_found: Response = Response({"response": "there is no user with nickname {}."})

        dont_have_alias: Response = Response({"response": "You don't have the \"{}\" alias!"})

        alias_invalid_name: Response = Response({"response": "Your alias name is not valid! "
                                                             "Your alias should only contain letters, numbers and "
                                                             "be 2-30 characters long."})

        user_has_no_alias: Response = Response({"response": "User {} has no registered aliases."})

        alias_table_headers: list[str] = [
                "Alias Name", "Description", "Invokes", "Arguments", "Links to", "Updated", "Created"]

        alias_table_replaces: list[str] = ["No description", "No arguments", "None", ]

        alias_table_name: str = "{} aliases"

        class Add(BaseTranslation):
            no_command_to_add: Response = Response({"response": "You didn't send a command! "
                                                                "Usage: {}alias add (name) (command) (...arguments)"})

            alias_name_conflict: Response = Response({"response": "Cannot add alias \"{}\" - you already have one! "
                                                                  "You can either \"edit\" its definition, \"rename\" "
                                                                  "it or \"remove\" it."})

            alias_crated: Response = Response({"response": "Your alias \"{}\" has been created successfully."})

            command_dont_exist: Response = Response({"response": "Cannot create alias! "
                                                                 "The command \"{}\" does not exist."})

        class Check(BaseTranslation):
            user_alias_list: Response = Response({"response": "List of your aliases: {} | Detailed list: {}"})

            no_alias_found: Response = Response({"response": "Could not find {} in {} aliases or any of your aliases!"})

            list_of_alias_of: Response = Response({"response": "List of {} aliases: {}"})

            list_of_special_case: Response = Response({"response": "Special case!\n "
                                                                   "Your alias \"{0}\": {1}\n "
                                                                   "List of {0}'s aliases: {2}"})

            alias_not_found: Response = Response({"response": "{} don't have the \"{}\" alias!"})

            appendix: str = "This alias is a link to \"{}\" made by {}."

            alias_deleted: Response = Response({"response": "{} alias is a link to a different alias, "
                                                            "but the original has been deleted."})

            appendix_message: Response

            message: str = "{} alias \"{}\" have the arguments: {} {}"

            normal_message: Response = Response({"response": "{} || Link: {}"})

        class Copy(BaseTranslation):
            user_not_provided: Response = Response({"response": "No target user provided!"})

            alias_not_provided: Response = Response({"response": "No target alias provided!"})

            target_alias_invalid_name: Response = Response({"response": "The copied alias's name is not "
                                                                        "valid and therefore can't be copied!"})

            no_alias_found: Response = Response({"response": "I couldn't find {} in user {}!"})

            link_to_a_link: Response = Response({"response": 'You cannot copy links to other aliases. '
                                                             'Instead, use {}alias copy {} {}'})

            copy_success: Response = Response({"response": "Alias \"{}\" copied successfully."})

            copy_with_name_of: Response = Response({"response": "Alias \"{}\" copied successfully. "
                                                                "With the name \"{}\"."})

        class Describe(BaseTranslation):
            no_args_to_parse: Response = Response({"response": "You didn't provide a alias or description! "
                                                               "Use: {}alias describe (name) (...description)"})

            description_updated: Response = Response({"response": "The description of alias \"{}\" "
                                                                  "has been updated successfully."})

            description_reverted: Response = Response({"response": "The description of alias \"{}\" "
                                                                   "has been reset successfully."})

        class Edit(BaseTranslation):
            no_args_provided: Response = Response({
                "success": False,
                "response": "No alias or command name provided!"})

            edit_link: Response = Response({
                "success": False,
                "response": "You cannot edit links to other aliases!"})

            edit_success: Response = Response({
                "success": False,
                "response": 'Your alias "{}" has been successfully edited.'})

            command_dont_exist: Response = Response({
                "success": False,
                "response": "Cannot edit alias! The command \"{}\" does not exist."})

        class Link(BaseTranslation):
            link_no_args: Response = Response({"response": "You didn't provide a user or alias name! "
                                                           "Use: {}alias link (user) (alias name)"})

            alias_name_already_exists: Response = Response({"response": "Cannot link a new alias - "
                                                                        "you already have an alias with that name!"})

            user_dont_has_alias: Response = Response({"response": 'The provided user does not have the alias "{}"!'})

            link_with_invalid_name: Response = Response({"response": 'The linked alias name is not valid! {}'})

            link_name_string: str = ', with a custom name of "{}".'

            link_to_link: Response = Response({"response": "You tried to create a link from a linked alias "
                                                           "(alias {} by {}), so I used the original as your "
                                                           "template. When the original changes, yours will too."})

            link_success: Response = Response({"response": 'Alias successfully linked{} '
                                                           'When the original changes, yours will too.'})

        class Remove(BaseTranslation):
            no_alias_name_provided: Response = Response({
                "success": False,
                "response": "No alias name provided!"})

            alias_removed: Response = Response({
                "success": False,
                "response": 'Your alias "{}" has been successfully removed.'})

        class Rename(BaseTranslation):
            no_name_provided: Response = Response({
                "success": False,
                "response": "You must provide both the current alias name and the new one!"})

            alias_already_exists: Response = Response({
                "success": False,
                "response": 'You already have the "{}" alias!'})

            alias_renamed: Response = Response({
                "success": False,
                "response": 'Your alias "{}" has been successfully renamed to "{}".'})

    class Chance(BaseTranslation):
        random_percentage: Response = Response({"response": "{:.2f}%."})

    class Choice(BaseTranslation):
        base_separators: list[str] = [",", " "]
        choice_separators: list[str] = base_separators + ["or"]
        # On translation use choice_separators: list[str] = EnTranslations.Choice.base_separators + list of strings.
        # See portuguese as exemple.
        chosen_option: Response = Response({"response": "{}"})

    class Count(BaseTranslation):
        character_count: Response = Response({
                "response": "There is a total of {} characters. "
                            "Of these, {} are punctuation marks, {} are uppercase letters, "
                            "and {} are special characters."})

    class HyperTranslate(BaseTranslation):
        # User bot.apis.translate.constants.GOOGLE_LANGUAGES_TO_CODES as reference for the lang
        lang: str = "en"

        quantity_error: Response = Response({"response": "You must specify the number of times the text will be "
                                                         "translated. Example: `{}hypertranslate 10 <text>`"})

        starter_string: str = "Translating the text..."

        unexpected_error: Response = Response({"response": "The text could not be translated."})

        translation: Response = Response({"response": "{}"})

    class NSFW:
        class Imgur(BaseTranslation):
            links: Response = Response({"response": ""})

            time_message: str = "Time: {} "

            all_images_embed: str = "All generated images: {} "

            all_images_embed_time: str = "Time: {} || All images: {} "

            timeout: Response = Response({"response": "100 seconds have passed, and I couldn't generate it. "
                                                      "Please wait a bit and try again."})

        class ImgurRepeated(BaseTranslation):
            links_repeated: Response = Response({"response": "Total number of repeated images: {} || Images: {}"})
            no_repeated: Response = Response({"response": "No repeated images."})

        class Boru(BaseTranslation):
            original: str = "Original"
            preview: str = "Preview"
            pls_wait = "por favor espera um pouco, estou gerando os links."
            unexpected_error: Response = Response({"success": False, "response": "{}"})
            success: Response = Response({"response": "{}"})
            too_much_tags: Response = Response({"response": "Quantidade de tags ultrapassou o limite permitido de {}."})

    class RandomColor(BaseTranslation):
        response_url: Response = Response({"response": "#{} is {}. {}"})

    class Reverse(BaseTranslation):
        reversed_string: Response = Response({"success": False, "response": "{}"})

    class RandomLine(BaseTranslation):
        channel_not_found: Response = Response({"response": "I couldn't find any channel named @{}."})
        user_not_found: Response = Response({"response": "I couldn't find any user named @{}."})
        no_message_found: Response = Response({"response": "Couldn't find any message from @{} in @{}."})
        random_line: Response = Response({"response": "{} (sent {} ago by @{})"})

    class Scp(BaseTranslation):
        links: Response = Response({})
        unexpected_error: Response = Response({"response": "An error occurred, please try again."})

    class UpSideDown(BaseTranslation):
        upsidedown: Response = Response({"response": "{}"})

    class Wikihow(BaseTranslation):
        url: str = "https://www.wikihow.com/Special:Randomizer"
        links: Response = Response({})
        unexpected_error: Response = Response({"response": "An error occurred, please try again."})

    class Wikipedia(BaseTranslation):
        url: str = "https://wikipedia.org/wiki/Special:Random"
        links: Response = Response({})
        unexpected_error: Response = Response({"response": "An error occurred, please try again."})

    class Annotations(BaseTranslation):
        too_much_characters: Response = Response({"response": "The annotation must have a maximum of 450 characters."})
        title_too_long: Response = Response({"response": "The title must have a maximum of 32 characters."})
        too_few_characters: Response = Response({"response": "You forgot to send the annotation content."})
        annotation_created: Response = Response({"response": "Note successfully created. 📝 (ID: {})"})
        no_annotations_with_id: Response = Response({"response": "You don't have any annotation with ID {}."})
        all_annotations: Response = Response({"response": "Your annotations are the ones with ID: {}"})
        annotation_content: Response = Response({"response": "{}"})
        deleted: Response = Response({"response": "Your annotation with ID {} was successfully deleted. 🗑"})
        id_not_provided: Response = Response({"response": "{} is not a valid ID."})
        option_not_recognized: Response = Response({"response": "The valid options are only "
                                                                "\"add\" \"check\" \"delete\""})

    class Lottery(BaseTranslation):
        bets_values: list[Values] = bets_values
        past_base: list[str] = ["old"]
        current_base: list[str] = ["current", "present"]
        past: list[str] = past_base
        current: list[str] = current_base

        only_numbers: Response = Response({"response": "Only send numbers from 1 to 60."})
        duplicate_numbers: Response = Response({"response": "Please choose non-duplicate numbers."})
        not_enough_cookies: Response = Response({"response": "You don't have enough cookies to place a bet. "
                                                             "The minimum is 5 cookies."})
        not_enough_cookies_more_five: Response = Response({"response": "You don't have enough cookies to place a bet. "
                                                                       "The number of cookies you need is {}"})
        bet_place: Response = Response({"response": "The bet has been placed with the numbers {} and a value of {} "
                                                    "cookies. (ID: {})"})
        lottery_lock: Response = Response({"response": "Sorry, the lottery is closed while the results are being "
                                                       "computed."})
        timeout: Response = Response({"response": "You took too long to choose an option."})
        too_much_numbers: Response = Response({"response": "You cannot bet on more than 15 numbers."})
        minimum_bet: Response = Response({"response": "Please choose at least 3 numbers."})

        no_bet_id: Response = Response({"response": "You don't have any bet with this ID."})
        ticket_info: Response = Response({"response": "Ticket with numbers: {} worth {} created {} ago."})
        no_old_bets_found: Response = Response({"response": "You don't have any past/closed bets."})
        old_bets: Response = Response({"response": "Your past bets are: {}, with a total value of {}."})
        no_active_bets_found: Response = Response({"response": "You don't have any active bets in the current round."})
        active_bets: Response = Response({"response": "Your current bets are: {}, with a total value of {}."})
        no_bets: Response = Response({"response": "You haven't made any bets so far."})
        all_bets: Response = Response({"response": "All of your bets are: {}, with a total value of {}."})
        unknown_option: Response = Response({"response": "The lottery options are: \"create\" and \"check\"."})
        lottery_announce_messages: list[str] = [
                "In 30 minutes, the lottery will start calculating the results. The total prize is {}, use {}lottery "
                "create <numbers> to participate.",
                "In 15 minutes, the lottery will start calculating the results.",
                "In 1 minute, the lottery will start calculating the results.",
                "Lottery closed, starting to compute the results."]

        winners: str = ("The drawn numbers were: {}, all winners will be notified with a reminder with the "
                        "values and drawn numbers.")

        no_winners: str = ("The drawn numbers were: {}, there were no winners, the prize of {} has rolled over to the "
                           "next draw.")

        lottery_result_announce: str = "The lottery is over and here are the results: {}"

        remind_message: str = "You won {} cookies in the lottery! The winning tickets were: {}"

    class Cookies(BaseTranslation):
        def cookie_file(self):  # TODO: Ver se funfa.
            with open("bot/translations/en/extras/cookies.txt", "r", encoding="utf-8") as file:
                cookie_lines = file.readlines()
            return cookie_lines


        daily_limit_reached: Response = Response({"response": "Você ainda está em cooldown espere mais {} até a "
                                                              "proxima fornada! ⌛"})

        user_not_found: Response = Response({"response": "usuário {} ainda não foi registra e não usou nenhum comando "
                                                         "de cookie."})

        invalid_option: Response = Response({"response": "Escolha em uma das opções \"eat\", \"count\", "
                                                         "\"top\", \"gift\", \"stock\" ou \"sm\""})

        cookie_not_found: Response = Response({"response": "O usuário {} ainda não usou nenhum comando "
                                                           "relaciona aos cookies."})

        # Eat
        not_eat: Response = Response({"response": "você não comeu nada, uau!"})

        negative_eat: Response = Response({"response": "para comer {} cookies, você primeiro deve saber reverter a "
                                                       "entropia."})

        multiple_eat: Response = Response({"response": "você comeu {} cookies de uma só vez. 🥠"})

        eat: Response = Response({"response": "{}"})

        # Cookie Count
        cc_bot_nick: Response = Response({"response": "eu tenho cookies infinitos, e distribuo uma fração deles "
                                                      "para vocês."})

        @staticmethod
        def format_cookie_count(ctx: Context, *args: Any, **kwargs: Any):
            self = Response({})
            self.ctx = ctx
            self.success = kwargs.pop("success", True)
            self.response_list = kwargs.pop("response_list", None)
            self.handle = kwargs.pop("handle", None)
            self.is_response = True

            mention = kwargs.pop("mention", None)
            cookie: Cookies = kwargs.pop("cookie")

            comidos = f"já comeu {cookie.consumed} cookies 🥠," if cookie.consumed > 0 else ""
            stocked = f"tem {round(cookie.stocked)} estocados," if cookie.stocked > 0 else ""
            received = f"foi presenteado com {cookie.received}," if cookie.received > 0 else ""
            donated = f"presenteou {cookie.donated}," if cookie.donated > 0 else ""

            not_redeemed = cookie.not_redeemed()

            unclaimed = (
                f"e tem um total de {not_redeemed} não resgatados."
                if not_redeemed > 0
                else ""
            )
            total = f"e teve um total de cookies de {cookie.total} cookies que ja passaram na conta."
            response = f"{mention} {comidos} {stocked} {received} {donated} {unclaimed} {total}"

            self.response_string = response
            return self

        # Gift
        gift_bot_nick: Response = Response({"response": "eu não quero seu cookie."})

        gift_user_himself: Response = Response({"response": "você tentou presenteou você mesmo, uau!"})

        # User not found response

        # Cookie not found

        gift_on_cooldown_no_stock: Response = Response({"response": "você não têm nenhum cookie estocado e o cooldown "
                                                                    "dura mais {}."})

        # daily_limit response

        invalid_gift_amount: Response = Response({"response": "mande uma quantidade valida para presentear e não {}."})

        multiple_gift: Response = Response({"response": "você presenteou @{} com {} cookie(s) 🎁"})

        gift: Response = Response({"response": "você presenteou @{} com um cookie(s) 🎁"})

        gift_not_enough_cookies: Response = Response({"response": "para presentear você precisa primeiro resgatar o "
                                                                  "cookie."})

        # gift_not_enough_cookies: Response = Response({"response": "você so pode presentear {}, para presentear {} vai "
        #                                                           "ter que esperar mais {} guardando o "
        #                                                           "cookie diário. (não usar stock ou cookie)"})

        # Stock
        stock: Response = Response({"response": "você stockou {} cookies 🍪, o próximo sai em 6h."})

        stock_not_daily: Response = Response({"response": "você stockou {} cookies 🍪."})

        stock_not_enough_cookies: Response = Response({"response": "você so pode stockar {}."})

        # Top
        
        order_dict = {
            # Key         field      title
            "stocked": ("stocked", "stocked"),
            "streak": ("streak", "streak"),
            "consumed": ("consumed", "cookiers"),
            "donated": ("donated", "givers"),
            "received": ("received", "receivers"),
            "total": ("total", "total"),
        }

        ranks: Response = Response({"success": False, "response": "os ranks são: {}"})

        top10_ish: Response = Response(
            {
                "success": False,
                "response": "top {} {}: {} || Você está na posição {}º do ranking com {}.",
                "is_response": False,
            }
        )


        class SlotMachine(BaseTranslation):
            daily_limit_reached: Response = Response(
                {
                    "success": False,
                    "response": "você já usou seu cookie diário, a próxima fornada sai a meia noite! ⌛",
                    "is_response": False,
                }
            )
            invalid_amount: Response = Response(
                {
                    "success": False,
                    "response": "você esta tentando apostar {} mais so tem {} cookies não resgatados.",
                    "is_response": False,
                }
            )
            daily_win: Response = Response(
                {
                    "success": False,
                    "response": "[{}] você usou seu cookie diário e ganhou {} cookies!",
                    "is_response": False,
                }
            )
            daily_single_loss: Response = Response(
                {
                    "success": False,
                    "response": "[{''.join(fruits)}] você perdeu seu cookie diário...",
                    "is_response": False,
                }
            )
            not_daily_multiple_loss: Response = Response(
                {
                    "success": False,
                    "response": "[{}] você usou seu cookie diário não resgatado e ganhou {} cookies!",
                    "is_response": False,
                }
            )
            not_daily_single_loss: Response = Response(
                {
                    "success": False,
                    "response": "[{}] você perdeu seu cookie diário não resgatado...",
                    "is_response": False,
                }
            )
            not_daily_multiple_win: Response = Response(
                {
                    "success": False,
                    "response": "você usou {} cookies diários não resgatados e ganhou {} cookies das seguintes "
                    "apostas: {}",
                    "is_response": False,
                }
            )
            not_daily_lost_everything: Response = Response(
                {
                    "success": False,
                    "response": "você usou {} cookies diários e perdeu tudo PoroSad",
                    "is_response": False,
                }
            )


    class Copy:
        class Copy(BaseTranslation):
            success: Response = Response({"success": False, "response": "o id da copypasta {}"})
            copy: Response = Response({"success": False, "response": "{}"})
            wrong_id: Response = Response(
                {"success": False, "response": "não existe copypasta com esse id."}
            )

        class DeleteCopy(BaseTranslation):
            deleted: Response = Response(
                {"success": False, "response": "a copypasta de id {} foi deletada."}
            )
            not_owner: Response = Response(
                {"success": False, "response": "você precisa ser o criador da copy para apagar."}
            )
            error: Response = Response(
                {"success": False, "response": "envie {}delcopy delete {} para deletar."}
            )

        class RandomCopy(BaseTranslation):
            success: Response = Response({"success": False, "response": "{}"})

    class Dungeons:
        dungeonrank_dict = dungeon_rank_dict

        class DungeonLevel(BaseTranslation):
            bot_nick: Response = Response(
                {"success": False, "response": "eu apenas crio as dungeons..."}
            )
            no_class_chosen: Response = Response(
                {"success": False, "response": "{} ainda não escolheu a nova classe"}
            )
            player_status: Response = Response(
                {
                    "success": False,
                    "response": "{} é {} ({}, {} XP) com {} dungeons ({} vitórias, {} derrotas, {:.2f}% winrate) ♦",
                    "is_response": False,
                }
            )
            player_not_found: Response = Response(
                {"success": False, "response": "{} ainda não entrou em nenhuma dungeon"}
            )

        class DungeonRank(BaseTranslation):
            winrate: Response = Response(
                {
                    "success": False,
                    "response": "top {} {}: {} || você é o {}º no ranking com {:.2f}% {}.",
                    "is_response": False,
                }
            )
            player_rank = "|| Você está na posição {}º no ranking com {} {}."
            normal: Response = Response({"success": False, "response": "top {} {}: {} {}"})

        class DungeonEnter(BaseTranslation):
            class_rank_up: Response = Response({"success": False, "response": "agora você é {}"})
            class_to_choose: Response = Response(
                {
                    "success": False,
                    "response": "antes de continuar, digite o comando e sua nova classe: {} ou {}",
                    "is_response": False,
                }
            )
            dungeon_result: Response = Response({"success": False, "response": "{}"})
            cooldown: Response = Response(
                {"success": False, "response": "aguarde {} para entrar em outra dungeon ⌛"}
            )
            class_choice: Response = Response(
                {"success": False, "response": "você escolheu {}! {}"}
            )
            class_first_choice: Response = Response(
                {
                    "success": False,
                    "response": "antes de continuar, escolha sua classe! "
                    "Digite {}ed Guerreiro(a), Arqueiro(a) ou Mago(a)",
                    "is_response": False,
                }
            )

        class DungeonFast(BaseTranslation):
            class_to_choose: Response = Response(
                {
                    "success": False,
                    "response": "antes de continuar, digite '{}ed' e sua nova classe: {} ou {}",
                    "is_response": False,
                }
            )
            cooldown: Response = Response(
                {"success": False, "response": "aguarde {} para entrar em outra dungeon ⌛"}
            )
            dungeon_result: Response = Response({"success": False, "response": "{}"})
            class_first_choice: Response = Response(
                {
                    "success": False,
                    "response": "antes de continuar, escolha sua classe! "
                    "Digite {}ed Guerreiro(a), Arqueiro(a) ou Mago(a)",
                    "is_response": False,
                }
            )

    class General:
        class BotInfo(BaseTranslation):
            info: Response = Response(
                {
                    "success": False,
                    "response": "estou conectado à {} canais, com {} comandos, "
                    '"feito" por @{} em Python (Twitchio). '
                    "Site do boto: {}",
                    "is_response": False,
                }
            )
            site: Response = Response({"success": False, "response": "{}"})
            uptime: Response = Response({"success": False, "response": "eu acordei há {}"})

        class Bug(BaseTranslation):
            bug_id: Response = Response(
                {"success": False, "response": "seu bug foi reportado 🐛 (ID {})"}
            )

        class Channels(BaseTranslation):
            quantity: Response = Response(
                {"success": False, "response": "estou conectado em {quantidade} canais."}
            )
            names: Response = Response({"success": False, "response": "{}"})

        class Color(BaseTranslation):
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "eu não encontrei ninguém com o nick de {} e isso também não é uma cor valida.",
                    "is_response": False,
                }
            )
            unexpected_error: Response = Response(
                {
                    "success": False,
                    "response": "Veja o nome da cor pelo HEX ou a cor de alguém pelo nick. "
                    "Ex: {}cor ff00ff ou {}cor {}",
                    "is_response": False,
                }
            )
            user_has_no_color = "o usuário {} não tem nenhuma cor salva."
            user_color = "{} cor salva"
            author_color = "sua cor salva é"
            response: Response = Response({"success": False, "response": "{}"})
            response_link: Response = Response(
                {"success": False, "response": "{} é {}. https://goo.gl/search?%23{} {}"}
            )

        class Dict(BaseTranslation):
            word_not_found: Response = Response(
                {"success": False, "response": "não encontrei a palavra {} no www.dicio.com.br"}
            )
            word: Response = Response(
                {"success": False, "response": "A palavra '{}' existe em {}"}
            )

        class Echo(BaseTranslation):
            echo: Response = Response({"success": False, "response": "{}"})

        class Help(BaseTranslation):
            command_site: Response = Response(
                {
                    "success": False,
                    "response": "veja todos os comandos: https://gorenmu.vercel.app/docs/intro",
                    "is_response": False,
                }
            )
            command: Response = Response(
                {"success": False, "response": "{}{}: {} | Comando no site: {}"}
            )
            command_aliases: Response = Response(
                {"success": False, "response": "{}{} ({}): {} | Comando no site: {}"}
            )

        class Join(BaseTranslation):
            join_message = (
                "Opa. Fui convidado a me instalar aqui, caso queira saber meus comandos entre em "
                '" {} " ou mande {}help. Se o bot cair manda whisper ou mensagem no '
                "chat do {} ."
            )
            already_in_channel_disabled: Response = Response(
                {
                    "success": False,
                    "response": "Eu nunca sai do canal {} e vc pôde me ativar novamente usando {}start !",
                    "is_response": False,
                }
            )
            joined: Response = Response(
                {"success": False, "response": "Entrei no canal com sucesso!"}
            )
            already_in_channel: Response = Response(
                {"success": False, "response": "Ja estou no canal {}!"}
            )

        class LastSeen(BaseTranslation):
            bot_nick: Response = Response(
                {"success": False, "response": "eu estou em todos os lugares, a todo momento..."}
            )
            author: Response = Response(
                {"success": False, "response": "você foi visto pela última vez aqui ☝️"}
            )
            author_not_found: Response = Response(
                {
                    "success": False,
                    "response": "@{name} ainda não foi registrado (não usou nenhum comando)",
                    "is_response": False,
                }
            )
            not_authorized: Response = Response(
                {"success": False, "response": "esse usuário optou por não permitir mencioná-lo"}
            )
            last_seen: Response = Response(
                {"success": False, "response": "@{} foi visto em @{} pela última vez: {} (há {})"}
            )

        class Leave(BaseTranslation):
            not_in_channel: Response = Response(
                {"success": False, "response": "Eu não estou no seu canal {}!"}
            )
            left: Response = Response({"success": False, "response": "{} removido com sucesso!"})

        class Nicks(BaseTranslation):
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "não encontrei ninguem com nome de {} no meu banco de dados.",
                    "is_response": False,
                }
            )
            nicks: Response = Response({"success": False, "response": "{}"})
            last_nick: Response = Response({"success": False, "response": "{} → {}"})
            no_nick: Response = Response(
                {"success": False, "response": "nenhuma mudança de nick registrada ainda."}
            )

        class Ping(BaseTranslation):
            ping: Response = Response(
                {"success": False, "response": "{} || RAM usada {} pelo python || {}"}
            )

        class PopOut(BaseTranslation):
            url: Response = Response(
                {"success": False, "response": "https://www.twitch.tv/popout/{}/chat?popout="}
            )

        class Preview(BaseTranslation):
            no_stream: Response = Response(
                {"success": False, "response": "este usuário não esta em live."}
            )
            response: Response = Response({"success": False, "response": "{}"})

        class Spam(BaseTranslation):
            content_not_valid: Response = Response(
                {"success": False, "response": "Por favor, digite um conteúdo para o spam."}
            )
            number_not_valid: Response = Response(
                {"success": False, "response": "'{}' não é um número."}
            )
            response: Response = Response({"success": False, "response": ""})

        class Suggest(BaseTranslation):
            suggest_id: Response = Response(
                {"success": False, "response": "sua sugestão foi anotada 📝 (ID {})"}
            )

    class Infos:
        class AccountAge(BaseTranslation):
            user_not_found: Response = Response(
                {"success": False, "response": "@{} é um usuário inválido."}
            )
            birthday_year: Response = Response(
                {"success": False, "response": "hoje completa {} ano que {} criou a conta 🎂"}
            )
            birthday_years: Response = Response(
                {"success": False, "response": "hoje completa {} anos que {} criou a conta 🎂"}
            )
            age: Response = Response(
                {"success": False, "response": "{} criou a conta em {} (há {})"}
            )

        class Avatar(BaseTranslation):
            user_not_found: Response = Response(
                {"success": False, "response": "minha foto de perfil: {} || {}"}
            )
            author_avatar: Response = Response(
                {"success": False, "response": "Usuário {} não exites."}
            )
            bot_avatar: Response = Response(
                {"success": False, "response": "sua foto de perfil: {} || {}"}
            )
            nick_avatar: Response = Response(
                {"success": False, "response": "foto de perfil de @{}: {} || {}"}
            )

        class FirstFollow(BaseTranslation):
            first_and_follow: Response = Response(
                {
                    "success": False,
                    "response": "{} seguiu primeiro @{} e foi seguido primeiro por @{}",
                    "is_response": False,
                }
            )
            not_first_but_followed: Response = Response(
                {
                    "success": False,
                    "response": "{} não segue ninguém e foi seguido primeiro por @{}",
                    "is_response": False,
                }
            )
            follow_but_not_followed: Response = Response(
                {
                    "success": False,
                    "response": "{} seguiu primeiro @{} e não é seguido por ninguém",
                    "is_response": False,
                }
            )
            alone: Response = Response(
                {"success": False, "response": "{} não segue e não é seguido por ninguém"}
            )

        class FollowAge(BaseTranslation):
            user_not_found: Response = Response(
                {"success": False, "response": "@{} é um usuário inválido."}
            )
            follow_yourself: Response = Response(
                {"success": False, "response": "{} não pode se seguir."}
            )
            not_followed: Response = Response({"success": False, "response": "{} não segue {}"})
            follow: Response = Response(
                {"success": False, "response": "{} seguiu {} em {} (há {})"}
            )

        class Live(BaseTranslation):
            bot_nick: Response = Response(
                {"success": False, "response": "eu sou um bot, não um streamer"}
            )
            user_not_found: Response = Response(
                {"success": False, "response": "@{channel} é um canal inválido"}
            )
            channel_offline: Response = Response(
                {"success": False, "response": "@{channel} está offline"}
            )
            stream: Response = Response(
                {
                    "success": False,
                    "response": "{} está streamando {} para {} viewers: {} (há {})",
                    "is_response": False,
                }
            )
            stream_with_print: Response = Response(
                {
                    "success": False,
                    "response": "{} está streamando {} para {} viewers: {} (há {}) || Print {}",
                    "is_response": False,
                }
            )

        class Title(BaseTranslation):
            bot_nick: Response = Response(
                {"success": False, "response": "eu sou um bot, não um streamer."}
            )
            user_not_found: Response = Response(
                {"success": False, "response": "@{} é um canal inválido"}
            )
            no_title_game: Response = Response(
                {"success": False, "response": "@{} não têm nem título e nem jogo configurado."}
            )
            no_title: Response = Response({"success": False, "response": "{} 🎮 {}"})
            title_no_game: Response = Response({"success": False, "response": "{} 📑 {}"})
            full_title: Response = Response({"success": False, "response": "{} 📑 {} | 🎮 {}"})

    class Interactive:
        class Fight(BaseTranslation):
            options: list[str] = fight_option
            bot_nick: Response = Response(
                {"success": False, "response": "você nunca conseguiria me derrotar..."}
            )
            internal_fight: Response = Response(
                {"success": False, "response": "você iniciou uma luta interna..."}
            )
            already_fight: Response = Response(
                {"success": False, "response": "@{} já está sendo desafiado por @{}!"}
            )
            result: Response = Response({"success": False, "response": "{}"})
            refused: Response = Response(
                {"success": False, "response": "@{} recusou o desafio contra @{} LUL"}
            )
            timeout: Response = Response(
                {"success": False, "response": "@{} não respondeu ao seu desafio a tempo"}
            )

        class Hug(BaseTranslation):
            bot: Response = Response({"success": False, "response": "🤗"})
            yourself: Response = Response(
                {"success": False, "response": "você tentou se abraçar..."}
            )
            hug: Response = Response({"success": False, "response": "você abraçou @{} 🤗"})

        class Kiss(BaseTranslation):
            bot: Response = Response({"success": False, "response": "😳"})
            yourself: Response = Response(
                {"success": False, "response": "você tentou se beijar..."}
            )
            kiss: Response = Response(
                {"success": False, "response": "você deu um beijinho em @{} 😚"}
            )

        class Love(BaseTranslation):
            yourself: Response = Response(
                {"success": False, "response": "uma pessoa não pode ser shipada com ela mesma..."}
            )
            ship: Response = Response(
                {"success": False, "response": "@{} & @{}: {} com {}% de amor {}"}
            )

        class Pat(BaseTranslation):
            bot: Response = Response({"success": False, "response": "😊"})
            yourself: Response = Response(
                {"success": False, "response": "você tentou fazer cafuné em si mesmo..."}
            )
            pat: Response = Response({"success": False, "response": "você fez cafuné em @{} 😊"})

        class Penis(BaseTranslation):
            bot: Response = Response({"success": False, "response": "eu só tenho pen drive."})
            penis: Response = Response({"success": False, "response": "{} tem {}cm {}"})

        class Slap(BaseTranslation):
            bot: Response = Response({"success": False, "response": "vai bater na mãe 😠."})
            yourself: Response = Response(
                {"success": False, "response": "você se deu um tapa... 😕."}
            )
            slap: Response = Response(
                {"success": False, "response": "você deu um tapa em @{} 👋"}
            )

        class Tuck(BaseTranslation):
            bot: Response = Response({"success": False, "response": "eu não posso dormir agora."})
            yourself: Response = Response(
                {"success": False, "response": "você foi para a cama 🛏"}
            )
            tuck: Response = Response(
                {"success": False, "response": "você colocou @{} na cama 🙂👉🛏"}
            )

    class Markov:
        class Markov(BaseTranslation):
            channel_not_found: Response = Response(
                {"success": False, "response": "@canal não encontrado no meu banco de dados."}
            )
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "@{} usuário não encontrado no meu banco de dados.",
                    "is_response": False,
                }
            )
            no_start: Response = Response(
                {
                    "success": False,
                    "response": "não encontrei nenhuma mensagem com o inicio {} para iniciar a geração",
                    "is_response": False,
                }
            )
            markov_generated: Response = Response({"success": False, "response": "{}"})

    class Marry:
        class Marry(BaseTranslation):
            bot: Response = Response(
                {
                    "success": False,
                    "response": "não fui programado para fazer parte de um relacionamento.",
                    "is_response": False,
                }
            )
            yourself: Response = Response(
                {"success": False, "response": "você não pode se casar com você mesmo..."}
            )
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "@{} ainda não foi registrado! (não usou nenhum comando)",
                    "is_response": False,
                }
            )
            proposal_already_in_progress: Response = Response(
                {
                    "success": False,
                    "response": "antes você precisa responder ao pedido de @{}! Digite 'yes' ou 'no",
                    "is_response": False,
                }
            )
            someone_arrived_first: Response = Response(
                {
                    "success": False,
                    "response": "@{} chegou primeiro e já fez uma proposta à mão de @{}",
                    "is_response": False,
                }
            )
            already_married: Response = Response(
                {"success": False, "response": "vocês dois já são casados... não se lembra?"}
            )
            author_limit_reached: Response = Response(
                {
                    "success": False,
                    "response": "você já está casado(a) com {} pessoas não é o suficiente?",
                    "is_response": False,
                }
            )
            limit_reached: Response = Response(
                {
                    "success": False,
                    "response": "@{} já está com o {} pessoas, não há espaço para mais um...",
                    "is_response": False,
                }
            )
            not_enough_cookies: Response = Response(
                {
                    "success": False,
                    "response": "para pagar a aliança e todo o casório, você deve juntar mais {} cookies.",
                    "is_response": False,
                }
            )

            proposal_message: str = (
                "você pediu a mão de @{}, o usuário deve digitar 'yes' ou 'no' / 'sim' ou 'não', 💐💍"
            )

            not_enough_cookies2: Response = Response(
                {
                    "success": False,
                    "response": "parece que @{} gastou todos os cookies que eram pra aliança... "
                    "o casamento precisou ser cancelado",
                    "is_response": False,
                }
            )
            proposal_accept: Response = Response(
                {
                    "success": False,
                    "response": "{}, você aceitou o pedido de @{}, felicidades para o casal! 🎉💞",
                    "is_response": False,
                }
            )
            no_proposal: Response = Response(
                {"success": False, "response": "{}, não há nenhum pedido de casamento para você."}
            )

            proposal_denied: Response = Response(
                {"success": False, "response": "{}, você recusou o pedido de casamento de @{} 💔"}
            )

            timeout: Response = Response(
                {
                    "success": False,
                    "response": "o tempo para pensar acabou, caso descidão se casar de novo use o comando novamente.",
                    "is_response": False,
                }
            )

        class Divorce(BaseTranslation):
            bot: Response = Response(
                {"success": False, "response": "eu nunca estaria casado com você."}
            )
            yourself: Response = Response(
                {"success": False, "response": "você não pode se livrar de você mesmo."}
            )
            not_married: Response = Response(
                {"success": False, "response": "você não está casado com ninguém."}
            )
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "@{} ainda não foi registrado! (não usou nenhum comando)",
                    "is_response": False,
                }
            )
            divorce: Response = Response(
                {
                    "success": False,
                    "response": "então, é isso... da próxima vez, case-se com alguém "
                    "que realmente te ame, e não qualquer pessoa por aí",
                    "is_response": False,
                }
            )
            wrong_person: Response = Response(
                {
                    "success": False,
                    "response": "você não sabe nem o nome da pessoa com quem está casado?",
                    "is_response": False,
                }
            )

        class MarryAge(BaseTranslation):
            bot: Response = Response(
                {"success": False, "response": "nunca me casarei com ninguém."}
            )
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "@{} ainda não foi registrado! (não usou nenhum comando)",
                    "is_response": False,
                }
            )
            not_married: Response = Response(
                {"success": False, "response": "{} não esta casado com ninguém."}
            )
            married: str = "@{} está casado com @{} há {}"
            divorced: str = "@{} está separado de @{} há {} e quem pediu o divórcio foi @{}"
            response: Response = Response({"success": False, "response": ""})

    class Pet:
        PetsDict: PetsDict = pets
        FromListToPetList = from_list_to_pet_list

        class Pet(BaseTranslation):
            bot: Response = Response(
                {
                    "success": False,
                    "response": "eu tenho todos os pets, e ofereço alguns pra vocês",
                    "is_response": False,
                }
            )
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "@{} ainda não foi registrado! (não usou nenhum comando)",
                    "is_response": False,
                }
            )
            mention_denied: Response = Response(
                {"success": False, "response": "@{} optou por não permitir ser mencionado."}
            )
            pets: Response = Response({"success": False, "response": "{} possui {}"})
            no_pets: Response = Response(
                {
                    "success": False,
                    "response": "adquira um dos pets disponíveis ({}petlist) em troca de cookies.",
                    "is_response": False,
                }
            )
            user_no_pets: Response = Response(
                {"success": False, "response": "{} não possui nenhum pet."}
            )

        class PetBuy(BaseTranslation):
            no_cookies: Response = Response(
                {
                    "success": False,
                    "response": "comece a estocar cookies para adquirir um pet ({}stock)",
                    "is_response": False,
                }
            )
            not_enough_cookies: Response = Response(
                {"success": False, "response": "estoque {} cookies para adquirir {}"}
            )
            name_too_large: str = (
                "vamos maneirar no tamanho do nome, " "tente novamente desta vez com um nome menor que 32 caracteres."
            )
            timeout: Response = Response(
                {"success": False, "response": "o tempo para comprar acabou tente novamente."}
            )
            timeout_response: Response = Response(
                {"success": False, "response": "você demorou de mais para responder."}
            )
            what_name: str = "qual nome você gostaria de da-lo?"
            are_you_sure: str = "tem certeza que deja nomear de {}? (yes ou no)"
            pet_name: str = "o seu pet sera nomeado {}"
            pet_buy: Response = Response(
                {"success": False, "response": "você adquiriu {} {} por {} cookies."}
            )
            no_options: Response = Response(
                {"success": False, "response": "escolha um dos pets disponíveis hoje ({}petlist)"}
            )

        class PetList(BaseTranslation):
            pet_list: Response = Response(
                {"success": False, "response": "pets disponíveis (adquira com {}petbuy): {}"}
            )

        class PetName(BaseTranslation):
            no_pets: Response = Response(
                {"success": False, "response": "Você não tem pets para dar nome."}
            )
            what_pet_to_name: str = (
                "qual dos pets você quer nomear: {}? " "(mande o número do pet que você gostaria de mudar.)"
            )
            timeout: Response = Response(
                {"success": False, "response": "você demorou de mais para responder."}
            )
            what_name: str = "qual nome você quer dar para {}?"
            new_name: Response = Response(
                {"success": False, "response": "o nome do pet foi mudado para {} ."}
            )

        class PetPat(BaseTranslation):
            no_pet_name: Response = Response(
                {"success": False, "response": "você não especificou o nome do pet."}
            )
            no_pets: Response = Response(
                {"success": False, "response": "você fez carinho em {} {}"}
            )
            pet_pat: Response = Response(
                {
                    "success": False,
                    "response": "adquira um dos pets disponíveis ({}petlist) em troca de cookies.",
                    "is_response": False,
                }
            )
            wrong_pet_name: Response = Response(
                {"success": False, "response": "você não tem um pet com este nome.."}
            )

        class PetSell(BaseTranslation):
            pass

    class Profile:
        class Mention(BaseTranslation):
            mention_on: Response = Response(
                {
                    "success": False,
                    "response": "outros usuários poderão mencionar você novamente nos comandos.",
                    "is_response": False,
                }
            )

        class NickName(BaseTranslation):
            nickname_too_large: Response = Response(
                {
                    "success": False,
                    "response": "o apelido {} é muito grande, por favor tente manter com no máximo 32 caracteres.",
                    "is_response": False,
                }
            )
            nickname_removed: Response = Response(
                {"success": False, "response": "seu apelido foi removido com sucesso!"}
            )
            nickname_changed: Response = Response(
                {"success": False, "response": "você alterou seu de apelido para {} com sucesso!"}
            )

        class SaveCity(BaseTranslation):
            city_removed: Response = Response(
                {"success": False, "response": "Cidade foi removida com sucesso!."}
            )
            city_added: Response = Response(
                {
                    "success": False,
                    "response": "Você salvou {} como sua cidade, agora basta usar {}weather.",
                    "is_response": False,
                }
            )

        class SaveColor(BaseTranslation):
            color_removed: Response = Response(
                {"success": False, "response": "a cor foi removida com sucesso!"}
            )
            color_added: Response = Response(
                {
                    "success": False,
                    "response": 'você salvou a cor {} e pode visualizá-la usando "{}color"',
                    "is_response": False,
                }
            )

        class UnMention(BaseTranslation):
            mention_off: Response = Response(
                {
                    "success": False,
                    "response": "agora outros usuários não poderão mais mencionar você nos comandos.",
                    "is_response": False,
                }
            )

    class Reminder:
        class Remind(BaseTranslation):
            bot: Response = Response(
                {
                    "success": False,
                    "response": "estou sempre aqui... não precisa me deixar lembretes.",
                    "is_response": False,
                }
            )
            user_not_found: Response = Response(
                {
                    "success": False,
                    "response": "esse usuário ainda não foi registrado. (não usou nenhum comando)",
                    "is_response": False,
                }
            )
            user_opt_out: Response = Response(
                {"success": False, "response": "o usuário {} optou por desligar os reminds para."}
            )
            author_too_much_reminds: Response = Response(
                {"success": False, "response": "já existem muitos lembretes seus pendentes..."}
            )
            user_too_much_reminds: Response = Response(
                {"success": False, "response": "já existem muitos lembretes pendentes para {}"}
            )
            time_not_found: Response = Response(
                {"success": False, "response": "não entendi o tempo que você me passou."}
            )
            remind_on_back: Response = Response(
                {
                    "success": False,
                    "response": "{} será lembrado disso na próxima vez que falar no chat 📝 (ID {})",
                    "is_response": False,
                }
            )
            dont_have_time_machine: Response = Response(
                {"success": False, "response": "eu ainda não inventei a máquina do tempo."}
            )
            minimum_time: Response = Response(
                {
                    "success": False,
                    "response": "o tempo mínimo para lembretes cronometrados é 1 minuto.",
                    "is_response": False,
                }
            )
            remind_on_time: Response = Response(
                {"success": False, "response": "{} será lembrado disso em {}. ⏲️(ID {})"}
            )

        class Reminds(BaseTranslation):
            remind_for: Response = Response(
                {"success": False, "response": "esse lembrete é para {}: {}."}
            )
            remind_timed_with_content: Response = Response(
                {"success": False, "response": "esse lembrete é para {} em {}: {}."}
            )
            remind_timed_without_content: Response = Response(
                {"success": False, "response": "esse lembrete era para {} há {}."}
            )
            remind_deleted: Response = Response(
                {"success": False, "response": "seu lembrete de ID {} foi deletado."}
            )
            remind_not_found: Response = Response(
                {"success": False, "response": "você não possui nenhum lembrete com esse ID."}
            )
            no_id_selected: Response = Response(
                {
                    "success": False,
                    "response": "você deve passar o ID do lembrete que quer deletar.",
                    "is_response": False,
                }
            )
            author_reminds: Response = Response(
                {"success": False, "response": "seus lembretes pendentes são os de ID: {}."}
            )
            author_dont_have_reminds: Response = Response(
                {"success": False, "response": "você não tem lembretes pendentes."}
            )

        class RemindListener(BaseTranslation):
            remind_timed_with_content: Response = Response(
                {"success": False, "response": "{} deixou um lembrete: {} (há {})"}
            )
            remind_timed_without_content: Response = Response(
                {"success": False, "response": "{} deixou um lembrete em branco (há {})"}
            )

    class Settings:
        class BanWord(BaseTranslation):
            word_added: Response = Response(
                {"success": False, "response": "esse já é um termo banido."}
            )
            word_already_on_list: Response = Response(
                {
                    "success": False,
                    "response": "não irei mais enviar mensagens que tiverem esse termo.",
                    "is_response": False,
                }
            )

        class Disable(BaseTranslation):
            command_dont_exist: Response = Response(
                {"success": False, "response": "esse comando não existe."}
            )
            command_cannot_be_disabled: Response = Response(
                {"success": False, "response": "não pode ser desativado."}
            )
            command_already_disabled: Response = Response(
                {"success": False, "response": '"{}" já está desativado.'}
            )
            command_disabled: Response = Response(
                {"success": False, "response": '"{}" foi desativado.'}
            )

        class Enable(BaseTranslation):
            command_dont_exist: Response = Response(
                {"success": False, "response": "esse comando não existe."}
            )
            command_reactivated: Response = Response(
                {"success": False, "response": '"{}" foi reativado.'}
            )
            command_already_activated: Response = Response(
                {"success": False, "response": '"{}" já está ativado.'}
            )

        class Prefix(BaseTranslation):
            prefix_invalid: Response = Response(
                {"success": False, "response": "este prefixo {prefixo} é invalido"}
            )
            prefix_invalid_or_absent: Response = Response(
                {"success": False, "response": "Esqueceu de mandar o prefixo ou ele é invalido."}
            )
            prefix_already_in_use: Response = Response(
                {"success": False, "response": "O canal ja esta usando o prefixo {prefixo}."}
            )
            prefix_changed: Response = Response(
                {"success": False, "response": 'O prefixo do canal foi alterado para "{}".'}
            )
            prefix_too_large: Response = Response(
                {
                    "success": False,
                    "response": "Atualmente eu so consigo armazenar prefixos de ate 2 caracteres o prefixo que você "
                    'tentou usar não é valido pois contem "{}" caracteres.',
                    "is_response": False,
                }
            )

        class Start(BaseTranslation):
            already_on: Response = Response({"success": False, "response": "já estou ligado ☕"})
            started: Response = Response({"success": False, "response": "você me ligou ☕"})

        class Stop(BaseTranslation):
            stopped: Response = Response({"success": False, "response": "você me desligou 💤"})

        class UnBanWord(BaseTranslation):
            word_removed: Response = Response(
                {"success": False, "response": '"{}" foi removido dos termos banidos.'}
            )
            word_not_found: Response = Response(
                {"success": False, "response": '"{}" não é um termo banidos.'}
            )

    class Tools:
        class Math(BaseTranslation):
            result: Response = Response({"success": False, "response": "{}"})
            error: Response = Response(
                {
                    "success": False,
                    "response": "não consegui calcular... lembre-se: use * para multiplicação, use / para divisão, "
                    "e use ponto em vez de vírgula para números decimais. {}",
                    "is_response": False,
                }
            )

        class Shorten(BaseTranslation):
            no_links_found: Response = Response(
                {"success": False, "response": "Use: `{}encurta <link>`"}
            )
            shorten_links: Response = Response(
                {"success": False, "response": "Aqui está os links: {}"}
            )
            shorten_link: Response = Response(
                {"success": False, "response": "Aqui está os link: {}"}
            )
            shorten_error: Response = Response(
                {"success": False, "response": "Não foi possível encurtar o link."}
            )

        class Time(BaseTranslation):
            time: Response = Response({"success": False, "response": "{}"})
            future_time: Response = Response({"success": False, "response": "em {}"})
            past_time: Response = Response({"success": False, "response": "há {}"})
            unit_not_found: Response = Response(
                {
                    "success": False,
                    "response": "as medidas suportadas atualmente são: anos, meses, semanas, dias, horas, "
                    "minutos e segundos. Caso nenhuma seja colocada, será dado o tempo completo convertido. ",
                    "is_response": False,
                }
            )
            too_much_time: Response = Response(
                {"success": False, "response": "tempo de mais para converter."}
            )

        class UserId(BaseTranslation):
            user_not_found: Response = Response(
                {"success": False, "response": "não achei nenhum usuário com esse id."}
            )
            id_or_name: Response = Response({"success": False, "response": "{}"})

        class Weather(BaseTranslation, WeatherTools):
            city_not_passed: Response = Response(
                {
                    "success": False,
                    "response": "você não enviou nenhuma cidade e não tem nenhuma cidade salva, "
                    "use {}savecity <cidade> para salvar uma cidade.",
                    "is_response": False,
                }
            )
            city_not_found: Response = Response(
                {
                    "success": False,
                    "response": "eu não encontrei nenhuma cidade com o nome de {}.",
                    "is_response": False,
                }
            )
            weather: Response = Response({"success": False, "response": ""})

            @staticmethod
            def format_weather(self: Response, ctx: Context, *args: Any, **kwargs: Any) -> Response:
                self.ctx = ctx
                success = kwargs.pop("success", True)
                response_list = kwargs.pop("response_list", None)
                handle = kwargs.pop("handle", None)
                self.is_response = True

                weather_obj = kwargs.pop("weather_obj")
                index = kwargs.pop("index")
                city = kwargs.pop("city")
                weather_str = kwargs.pop("weather_str")
                emoji = kwargs.pop("emoji")
                wind_direction = kwargs.pop("wind_direction")

                self.success = success
                self.response_list = response_list
                self.handle = handle

                current_temp, apparent_temp, max_temp, pressure, humidity, wind, precipitation = (
                    weather_obj.current_weather.temperature,
                    weather_obj.hourly.apparent_temperature[index],
                    weather_obj.daily.temperature_2m_max[0],
                    weather_obj.hourly.pressure_msl[index],
                    weather_obj.hourly.relative_humidity_2m[index],
                    weather_obj.current_weather.wind_speed,
                    weather_obj.hourly.precipitation[index],
                )
                unit_temp, unit_press, unit_humid, unit_wind, unit_precip = (
                    weather_obj.hourly_units.apparent_temperature,
                    weather_obj.hourly_units.pressure_msl,
                    weather_obj.hourly_units.relative_humidity_2m,
                    weather_obj.hourly_units.wind_speed_10m,
                    weather_obj.hourly_units.precipitation,
                )

                weather_city = f"{city.display}. {weather_str.capitalize()} {emoji.strip()},"
                temp_string = (
                    f"temperatura de {current_temp} {unit_temp}, máxima de {max_temp} {unit_temp} "
                    f"e aparente de {apparent_temp} {unit_temp},"
                )
                press_string = f"{pressure} {unit_press},"
                humid_string = f"{humidity}{unit_humid},"
                wind_string = f"{wind}{unit_wind} {wind_direction}"
                precip_string = f"" if precipitation == 0 else f", e precipitação de {precipitation} {unit_precip}"

                self.response_string = (
                    f"{weather_city} {temp_string} {press_string} " f"{humid_string} {wind_string} {precip_string}"
                )
                return self

    class Tower:
        class EnterTower(BaseTranslation):
            class_rank_up: Response = Response({"success": False, "response": "agora você é {}"})
            class_to_choose: Response = Response(
                {
                    "success": False,
                    "response": "Antes de continuar, digite o comando e sua nova classe: {} ou {}",
                    "is_response": False,
                }
            )
            cooldown: Response = Response(
                {"success": False, "response": "aguarde {} para entrar continuar a escalada ⌛"}
            )
            tower_result: Response = Response({"success": False, "response": "{}"})
            class_choice: Response = Response(
                {"success": False, "response": "você escolheu {}! {}"}
            )
            class_first_choice: Response = Response(
                {
                    "success": False,
                    "response": "antes de continuar, escolha sua classe! {}ed  " "Guerreiro(a), Arqueiro(a) ou Mago(a)",
                    "is_response": False,
                }
            )

        class FastTower(BaseTranslation):
            class_to_choose: Response = Response(
                {
                    "success": False,
                    "response": "Antes de continuar, digite o comando e sua nova classe: {} ou {}",
                    "is_response": False,
                }
            )
            cooldown: Response = Response(
                {"success": False, "response": "aguarde {} para entrar continuar a escalada ⌛"}
            )
            tower_result: Response = Response({"success": False, "response": "{}"})
            class_first_choice: Response = Response(
                {
                    "success": False,
                    "response": "antes de continuar, escolha sua classe! {}et " "Guerreiro(a), Arqueiro(a) ou Mago(a)",
                    "is_response": False,
                }
            )

        class TowerLevel(BaseTranslation):
            bot_nick: Response = Response(
                {"success": False, "response": "Eu apenas conto as historias dos encontros."}
            )
            no_class_chosen: Response = Response(
                {"success": False, "response": "{} ainda não escolheu uma classe."}
            )
            player_status: Response = Response(
                {
                    "success": False,
                    "response": "{} é {} ({}, {} XP). Esta no andar {} zona {}, com um total de {} "
                    "encontros ({} vitórias, {} derrotas, {.2f}% winrate) ♦",
                    "is_response": False,
                }
            )
            player_not_found: Response = Response({"success": False, "response": ""})



    class Admin:
        class AddUser(BaseTranslation):
            user_not_found: Response = Response(
                {"success": True, "response": "não existe nenhum usuário com nick {}."}
            )
            user_response: Response = Response(
                {
                    "success": False,
                    "response": "as infos de {} foram adicionadas.",
                    "response_list": [],
                    "is_response": False,
                }
            )

        class AddBot(BaseTranslation):
            user_not_found: Response = Response(
                {"success": False, "response": "eu ainda não vi esse bot em nenhum chat."}
            )
            user_already_added: Response = Response(
                {"success": False, "response": "o bot {} ja esta registrado."}
            )
            user_added: Response = Response(
                {"success": True, "response": "o bot {} foi adicionado aos bots."}
            )

        class AllChannels(BaseTranslation):
            channels: Response = Response(
                {"success": False, "response": "aqui a lista de todos os canais que eu estou: {}"}
            )

        class Announce(BaseTranslation):
            success: Response = Response(
                {"success": False, "response": "O comando foi executado com sucesso."}
            )

        class ApiBot(BaseTranslation):
            added_with_success: Response = Response(
                {
                    "success": False,
                    "response": "O comando foi executado com sucesso. Com {} bots adicionados.",
                    "is_response": False,
                }
            )

        class ChannelLog(BaseTranslation):
            channel_already_added: Response = Response(
                {"success": False, "response": "Ja estou no canal {}."}
            )
            channel_added: Response = Response(
                {"success": True, "response": "Entrei no canal {}."}
            )

        class CookieGive(BaseTranslation):
            cookie_given: Response = Response(
                {"success": True, "response": "você deu {} para {}."}
            )

        class CountUser(BaseTranslation):
            user_quantity: Response = Response(
                {"success": True, "response": "têm {} usuários no banco de dados."}
            )

        class DBGrep(BaseTranslation):
            user_not_found: Response = Response(
                {"success": True, "response": "não existe nenhum usuário com nick {}."}
            )
            user_info: Response = Response(
                {
                    "success": False,
                    "response": "aqui as infos do usuário: {}.",
                    "response_list": [],
                    "is_response": False,
                }
            )
            channel_info: Response = Response(
                {"success": False, "response": "aqui as infos do canal: {}.", "response_list": []}
            )

        class DelFromDB(BaseTranslation):
            user_not_found: Response = Response(
                {"success": True, "response": "não existe nenhum usuário com nome {}."}
            )
            user_deleted: Response = Response(
                {"success": True, "response": "o usuário {} foi deletado do banco de dados."}
            )
            users_deleted: Response = Response(
                {
                    "success": True,
                    "response": "foi deletado {} usuários do canal {}.",
                    "response_list": [],
                    "is_response": False,
                }
            )

        class DisableNSFW(BaseTranslation):
            commands_disabled: Response = Response(
                {"success": True, "response": "NSFW foi desabilitado em {} canais."}
            )

        class LotteryStart(BaseTranslation):
            pass  # TODO: Fazer quando refizer o loterica_start

        class Nada(BaseTranslation):
            nada: Response = Response(
                {"success": True, "response": "O comando foi executado com asdfasdfafsadsaf."}
            )

        class Reload(BaseTranslation):
            commands_reloaded: Response = Response(
                {"success": True, "response": "Os comandos foram recarregados com sucesso."}
            )

        class Restart(BaseTranslation):
            success: Response = Response(
                {"success": True, "response": "O bot foi reiniciado com sucesso."}
            )
            unexpected_error: Response = Response(
                {"success": False, "response": "Houve um erro ao reiniciar o bot: {}"}
            )

        class RGit(BaseTranslation):
            git_pulled: Response = Response(
                {"success": True, "response": "O comando foi executado com sucesso."}
            )
