# Exceptions
Exceptions-user_not_found_id = I couldn't find any user with id { $id }.
Exceptions-user_not_found_name = I couldn't find any user named @{ $name }.
Exceptions-time_expired = Time { $time } has already expired.
Exceptions-no_content_provided = You need to provide content for this command.
Exceptions-too_much_characters = The message must have a maximum of 450 characters.
Exceptions-message_too_long = This message is too long.
Exceptions-no_id_provided = You need to provide a valid numeric ID.
Exceptions-id_not_valid = { $id } is not a valid ID.
Exceptions-user_not_provided = No target user provided!
Exceptions-guard_caught = You are not authorized to use the "{ $cmd }" command due to "{ $reason }". If you think this is an error, contact @{ $contact }.
Exceptions-unexpected_error = An error occurred, please try again: { $exception }
Exceptions-error = An unexpected error occurred. Please report it to @{ $dev } on whispers.
Exceptions-timeout = It's been 30 seconds and I can't find any valid links.
Exceptions-never_seen = I don't remember ever seeing any @{ $name }.
Exceptions-channel_not_found = I couldn't find any channel named @{ $name }.
Exceptions-dev_required = you need to be my creator to run this command.
Exceptions-owner_required = commands reserved for the bot owner.
Exceptions-command_on_cooldown = to use the command again, come back in { $time }.
Exceptions-disabled = this command is temporarily disabled.
Exceptions-not_implemented = Not implemented.
Exceptions-error_not_registered = an unexpected error occurred, please report the error to @{ $dev }.
Exceptions-command_not_pipeble = command { $cmd } can't be used with the pipe.
Exceptions-pipe_response_error = an error occurred while executing the previous command: { $error }
Exceptions-pipe_response = here is the response generated by the previous command: { $response }
Exceptions-lottery_seed = something terrible happened, contact "{ $contact }" here on Twitch using whispers.

## LanguageContext
LanguageContext-mention = you

## Verbs
LanguageContext_Verbs-cookies_second_person = have
LanguageContext_Verbs-cookies_third_person = has

LanguageContext_Verbs-positive = True,Yes,Yep,Yeah,y
LanguageContext_Verbs-negative = False,No,Nope,n
LanguageContext_Verbs-nothing = None,Nothing,Empty
LanguageContext_Verbs-separators = or
LanguageContext_Verbs-all = all

## TimeTools
TimeTools-strftime = %m/%d/%Y at %I:%M %p

# Humanize Units (format: plural,singular,abbreviation)
TimeTools-unit_years = years,year,y
TimeTools-unit_months = months,month,mo
TimeTools-unit_weeks = weeks,week,w
TimeTools-unit_days = days,day,d
TimeTools-unit_hours = hours,hour,h
TimeTools-unit_minutes = minutes,minute,min,m
TimeTools-unit_seconds = seconds,second,secs,sec,s
TimeTools-unit_milliseconds = milliseconds,millisecond,millisecs,milisec,milli
TimeTools-unit_microseconds = microseconds,microsecond,micro,us
TimeTools-unit_time = time,t

## Emotes
Emotes-happy = happy,KomodoHype,LUL
Emotes-pog = pog,PogChamp,KomodoHype
Emotes-sad = sad,BibleThump,FeelsBadMan
Emotes-love = love,bleedPurple,otterLove
Emotes-hug = hug,GivePLZ
Emotes-pat = pat,CoolCat
Emotes-hit = hit,PunchTree
Emotes-okay = okay,OkHand,SeemsGood
Emotes-bed = bed,ResidentSleeper

## GenericWait
GenericWait-already_in_action = A { $action } is already happening between @{ $user1 } and @{ $user2 }
GenericWait-accept = yes,y
GenericWait-reject = no,n
