site_name: Gorenmu Comandos
site_url: http://localhost:3400/pt_br/
docs_dir: '../../docs/pt_br/'
site_dir: '../../generated/pt_br/'
repo_url: https://github.com/MrChuw/Gorenmu/

theme:
  name: material  
  favicon: assets/images/favicon.png
  icon:
    logo: logo
  custom_dir: '../../overrides/'
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.prune
    - navigation.indexes
    - toc.follow
  palette:
    scheme: slate
    primary: bot
    accent:  bot


plugins:
  - search:
      lang: pt_br
  # - privacy
  - minify:
      minify_html: true
  - blog:
      post_excerpt_separator: <!-- more -->
  - rss:
      # match_path: blog/posts/.*
      use_git: false
      date_from_meta:
        as_creation: date.created
      categories:
        - categories
        - tags

extra:
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: Português
      link: /pt_br/
      lang: pt-BR



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Página Inicial: index.md
  - Changelog: blog/index.md
  - Comandos:
      - comandos/index.md
      - Pipe: comandos/pipe.md
      - Afk: comandos/afk.md
      - Isafk: comandos/isafk.md
      - Rafk: comandos/rafk.md
      - Alias: comandos/alias.md
      - Chance: comandos/chance.md
      - Choice: comandos/choice.md
      - Count: comandos/count.md
      - Hypertranslate: comandos/hypertranslate.md
      - Randomcolor: comandos/randomcolor.md
      - Reverse: comandos/reverse.md
      - Randomline: comandos/randomline.md
      - Upsidedown: comandos/upsidedown.md
      - Wikihow: comandos/wikihow.md

      - NSFW:
        - Imgur: comandos/imgur.md
        - Imgur_Repeated: comandos/imgur_repeated.md
      - Dev:
        - Nada: comandos/nada.md
        - Reload: comandos/reload.md


